//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowiedzMiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ankiety
    {
        public int id { get; set; }
        public System.DateTime data { get; set; }
        public int id_uzytkownika { get; set; }
        public string komentarz { get; set; }
    }
}
