//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowiedzMiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownicy
    {
        public int id { get; set; }
        public string imie { get; set; }
        public string haslo { get; set; }
    }
}
